// Generated by `wrangler types` - do not edit directly
// This file contains type definitions for Cloudflare Worker bindings

export {};

declare global {
  interface Env {
    R2_VFX: R2Bucket;
  }
}

/**
 * R2 Bucket interface for Cloudflare Workers
 * Provides methods for interacting with Cloudflare R2 object storage
 */
declare abstract class R2Bucket {
  /**
   * Retrieves an object from the bucket
   */
  get(key: string, options?: R2GetOptions): Promise<R2Object | null>;

  /**
   * Stores an object in the bucket
   */
  put(
    key: string,
    value: ReadableStream<Uint8Array> | ArrayBuffer | ArrayBufferView | string,
    options?: R2PutOptions
  ): Promise<R2Object>;

  /**
   * Deletes an object from the bucket
   */
  delete(key: string): Promise<void>;

  /**
   * Lists objects in the bucket
   */
  list(options?: R2ListOptions): Promise<R2Objects>;

  /**
   * Gets the metadata for an object without retrieving its contents
   */
  head(key: string): Promise<R2Object | null>;
}

interface R2Object {
  key: string;
  version: string;
  size: number;
  etag: string;
  httpEtag: string;
  uploaded: Date;
  httpMetadata?: R2HTTPMetadata;
  customMetadata?: Record<string, string>;
  range?: R2Range;
  body: ReadableStream<Uint8Array>;
  bodyUsed: boolean;
  arrayBuffer(): Promise<ArrayBuffer>;
  text(): Promise<string>;
  json<T>(): Promise<T>;
  blob(): Promise<Blob>;
  writeHttpMetadata(headers: Headers): void;
}

interface R2GetOptions {
  range?: R2Range | string;
  onlyIf?: R2Conditional | Headers;
}

interface R2PutOptions {
  onlyIf?: R2Conditional | Headers;
  httpMetadata?: R2HTTPMetadata | Headers;
  customMetadata?: Record<string, string>;
}

interface R2ListOptions {
  limit?: number;
  prefix?: string;
  cursor?: string;
  delimiter?: string;
  include?: ("checksums" | "httpMetadata" | "customMetadata")[];
}

interface R2Objects {
  objects: R2Object[];
  truncated: boolean;
  cursor?: string;
  delimitedPrefixes?: string[];
}

interface R2HTTPMetadata {
  contentType?: string;
  contentLanguage?: string;
  contentDisposition?: string;
  contentEncoding?: string;
  cacheControl?: string;
  cacheExpiry?: number;
}

interface R2Range {
  offset?: number;
  length?: number;
  suffix?: number;
}

interface R2Conditional {
  etagMatches?: string;
  etagDoesNotMatch?: string;
  uploadedBefore?: Date;
  uploadedAfter?: Date;
}
