name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - uses: actions/checkout@v7 # Uploads repository content to the runner
      with:
        repository: "vash-fiery/vashfx-homepage" # The one of the available inputs, visit https://github.com/actions/checkout#readme to find more
    - uses: actions/labeler@v7
      with:
        configuration-path: '.github/labeler.yml'
